---
- name: Set debconf vars
  action: raw sudo echo mysql-server mysql-server/root_password password {{ mysql_root_password }} | sudo /usr/bin/debconf-set-selections

- name: Set debconf vars
  action: raw sudo echo mysql-server mysql-server/root_password_again password {{ mysql_root_password }} | sudo /usr/bin/debconf-set-selections

- name: Install mysql database
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - python-mysqldb
    - mysql-client
    - mysql-server
  become: yes
  become_method: sudo